- name: Mount SMB share
  mount:
    src: "//{{ nas_ip_address }}/configs/docker-volumes"
    path: /mnt/docker-volumes
    fstype: cifs
    opts: "username={{ nas_share_username }},password={{ nas_share_password }}"
    state: mounted
  no_log: true
