- name: Install Home Assistant
  docker_container:
    name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - "{{ docker_volumes_host_path }}/home-assistant/config:/config"
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    env:
      TZ: "America/New_York"
    recreate: yes
    restart_policy: unless-stopped
    state: started