- name: Disallow PermitRootLogin
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin yes"
    validate: sshd -t -f %s

- name: Disallow PasswordAuthentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication yes"
    validate: sshd -t -f %s

- name: Restart SSHD service
  service:
    name: sshd
    state: restarted
