- name: Creates path for promtail volume if not exists
  file:
    path: "{{ docker_volumes_host_path }}/promtail"
    state: directory

- name: Creaet promtail-config.yml file from template
  template:
    src: promtail-config.j2
    dest: "{{ docker_volumes_host_path }}/promtail/promtail-config.yml"

- name: Install Promtail
  docker_container:
    name: promtail
    image: grafana/promtail:latest
    published_ports:
      - 9007:9080
    volumes:
      - /var/log:/var/log
      - "{{ docker_volumes_host_path }}/promtail:/etc/promtail"
    command: -config.file=/etc/promtail/promtail-config.yml
    restart_policy: unless-stopped
    recreate: yes
    state: started
