- name: Install Grafana
  docker_container:
    name: grafana
    image: grafana/grafana:latest
    user: "0:0"
    published_ports:
      - 9003:3000
    volumes:
      - "{{ docker_volumes_host_path }}/grafana:/var/lib/grafana"
    restart_policy: unless-stopped
    recreate: yes
    state: started
