- name: Install Node Exporter
  become: false
  docker_container:
    name: node-exporter
    image: quay.io/prometheus/node-exporter:latest
    volumes:
      - /:/host:ro,rslave
    command: '--path.rootfs=/host'
    networks:
      - name: host
    pid_mode: host
    recreate: yes
    restart_policy: unless-stopped
    state: started
