---
version: "3"

# Reference https://github.com/pi-hole/docker-pi-hole/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/New_York'
      PIHOLE_DNS_: 1.1.1.1;1.0.0.1
      WEBTHEME: 'default-dark'
      WEBPASSWORD: password

    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped