- name: Install Duplicati
  become: false
  docker_container:
    name: duplicati
    image: lscr.io/linuxserver/duplicati:latest
    recreate: yes
    published_ports:
      - 8200:8200
    volumes:
      - /var/lib/docker/volumes/duplicati/config:/config
      - /var/lib/docker/volumes/duplicati/backups:/backups
      - /var/lib/docker/volumes/duplicati/source:/source
      - /var/lib/docker/volumes:/docker/volumes
      - /mnt/docker-volumes:/docker-volumes
    restart_policy: always
    env:
      PUID: "0"
      PGID: "0"
      TZ: "America/New_York"
    state: started