- name: Install Duplicati
  docker_container:
    name: duplicati
    image: lscr.io/linuxserver/duplicati:latest
    published_ports:
      - 8200:8200
    volumes:
      - "{{ docker_volumes_host_path }}/duplicati/config:/config"
      - "{{ docker_volumes_host_path }}:/source"
      - "{{ docker_volumes_nas_path }}/backups:/backups"
    env:
      PUID: "0"
      PGID: "0"
      TZ: "America/New_York"
    recreate: yes
    restart_policy: unless-stopped
    state: started