- name: Install Loki plugin to get docker container logs
  community.docker.docker_plugin.docker_plugin:
    plugin_name: grafana/loki-docker-driver:latest
    alias: loki
    state: enable
  register: loki_plugin_result

- name: daemon.json file from template
  template:
    src: daemon.j2
    dest: /etc/docker/daemon.json
  register: template_result

- name: Restart Docker daemon
  systemd:
    name: docker
    state: restarted
  when: loki_plugin_result.changed or template_result.changed
