# Variables needed for this role:
#   - ansible_become_password (to login as sudo for first run)
#   - initial_hosts (defined in playbook)
#   - initial_user
#   - inital_user_new_password
#   - ansible_username

- name: Secure inital user password
  user:
    name: "{{ initial_user }}"
    password: "{{ inital_user_new_password | password_hash('sha512') }}"

- name: Create ansible user and add to sudo group
  user:
    name: "{{ ansible_username }}"
    groups: sudo
    append: true

- name: Add ansible user public key to authorized_keys
  authorized_key:
    user: "{{ ansible_username }}"
    key: "{{ lookup('file', '~/.ssh/ansible.pub') }}"

- name: Add sudoers file for ansible user
  file:
    path: "/etc/sudoers.d/{{ item }}"
    owner: root
    group: sudo
    state: touch
  loop:
    - "{{ ansible_username }}"
    - "{{ initial_user }}"

- name: Allow passwordless sudo
  lineinfile:
    dest: "/etc/sudoers.d/{{ item }}"
    line: "{{ item }}	ALL=(ALL) NOPASSWD: ALL"
    validate: visudo -cf %s
  loop:
    - "{{ ansible_username }}"
    - "{{ initial_user }}"

- name: Disallow PermitRootLogin
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin no"
    validate: sshd -t -f %s

- name: Disallow PasswordAuthentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
    validate: sshd -t -f %s

- name: Restart SSHD service
  service:
    name: sshd
    state: restarted
