# Variables needed for this role:
#   ansible_default_vars.yaml
#   - ansible_username (user that ansible will create and use)
#   - ansible_become_password (to login as sudo for first run)
#   - ansible_ssh_private_key (key ansible will use for first run)
#   secure_server/vars/main.yaml
#   - initial_hosts (which machine)
#   - initial_user (user used for first run)
#   - initial_user_new_password (reset initial_user's password to something secure)

- name: Create ansible user and add to sudo group
  user:
    name: "{{ ansible_username }}"
    groups: sudo
    append: true

- name: Add SSH key for ansible user
  authorized_key:
    user: "{{ ansible_username }}"
    key: "{{ lookup('file', '~/.ssh/ansible.pub') }}"

- name: Add sudoers.d files for users
  file:
    path: "/etc/sudoers.d/{{ item }}"
    owner: root
    group: sudo
    state: touch
  loop:
    - "{{ ansible_username }}"
    - "{{ initial_user }}"

- name: Allow passwordless sudo for users
  lineinfile:
    dest: "/etc/sudoers.d/{{ item }}"
    line: "{{ item }}	ALL=(ALL) NOPASSWD: ALL"
    validate: visudo -cf %s
  loop:
    - "{{ ansible_username }}"
    - "{{ initial_user }}"

- name: Disallow PermitRootLogin
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin no"
    validate: sshd -t -f %s

- name: Disallow PasswordAuthentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
    validate: sshd -t -f %s

- name: Restart SSHD service
  service:
    name: sshd
    state: restarted

- name: Secure inital user password
  user:
    name: "{{ initial_user }}"
    groups: sudo
    append: true
    password: "{{ initial_user_new_password | password_hash('sha512') }}"
