# Variables needed for this role:
#   - portainer_encrypted_password (password for portainer)
- name: Install portainer
  become: true # should be false, making true for docker vm
  docker_container:
    name: portainer
    image: portainer/portainer-ce
    command: --admin-password "{{ portainer_encrypted_password }}"
    published_ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    recreate: yes
    restart_policy: unless-stopped
    state: started
