- name: Install Uptime Kuma
  docker_container:
    name: uptime-kuma
    image: louislam/uptime-kuma:1
    published_ports:
      - 9001:3001
    volumes:
      - "{{ docker_volumes_host_path }}/uptime-kuma/data:/app/data"
    recreate: yes
    restart_policy: unless-stopped
    state: started
