- name: Install Uptime Kuma
  become: true
  docker_container:
    name: uptime-kuma
    image: louislam/uptime-kuma:1
    published_ports:
      - 9001:3001
    volumes:
      - "{{ docker_volumes_path_on_host }}/uptime-kuma/data:/app/data"
    recreate: yes
    restart_policy: always
    state: started
