- name: Install Heimdall
  docker_container:
    name: heimdall
    image: lscr.io/linuxserver/heimdall:latest
    published_ports:
      - 9004:80
      - 443:443
    volumes:
      - "{{ docker_volumes_path_on_host }}/heimdall/config:/config"
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "America/New_York"
    recreate: yes
    restart_policy: unless-stopped
    state: started