---
- name: Install and setup monitoring
  hosts: monitoring
  become: true
  remote_user: "{{ ansible_username }}"

  vars_files:
    - vars/ansible_default_vars.yaml

  vars:
    docker_volumes_host_path: "{{ docker_volumes_path_on_host }}/monitoring"
    docker_volumes_nas_path: "{{ docker_volumes_path_on_nas }}/monitoring"

  roles:
    - apt-update
    - mount-nas
    - docker
    - loki-plugin
    - portainer
    - promtail
    - node-exporter
    - cadvisor # skipped if on raspberry pi
    - grafana
    - loki
    - prometheus
    - uptime-kuma
    - guacamole
    - watchtower
    - duplicati
