- name: Install Watchtower
  become: false
  docker_container:
    name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env:
      TZ: "America/New_York"
      WATCHTOWER_MONITOR_ONLY: "false"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_SCHEDULE: "0 0 4 * * 1"
    recreate: yes
    restart_policy: unless-stopped
