- name: Install Watchtower container
  docker_container:
    name: watchtower
    image: containrrr/watchtower
    command: "--schedule 0 1 * * *"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart_policy: always
